site_name: Trubrics docs
site_url: https://docs.trubrics.com
site_description: AI product analytics.
theme:
  name: material
  favicon: static/favicon.ico
  logo: static/logo-white.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Montserrat
  features:
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
extra_css:
  - stylesheets/extra.css
nav:
  - Quickstart: index.md
  - New to Trubrics?:
    - What is Trubrics?: new_to_trubrics/what_is_trubrics.md
    - What events to track?: new_to_trubrics/what_to_track.md
    - Core concepts: new_to_trubrics/core_concepts.md
  - Javascript SDK: track_events/sdks/javascript.md
  - Python SDK: track_events/sdks/python.md
  - Integrations:
    - Segment: track_events/integrations/segment.md
  - API reference:
    - api_reference/index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
  - md_in_html
copyright: Copyright &copy 2024 Trubrics Ltd.
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/trubrics
    - icon: fontawesome/brands/discord
      link: https://discord.gg/BPKTNxxz
plugins:
  - mkdocs-video