site_name: trubrics docs
site_url: https://docs.trubrics.com
site_description: AI product analytics.
theme:
  name: material
  favicon: static/favicon.ico
  logo: static/logo-white.png
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Montserrat
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
extra_css:
  - stylesheets/extra.css
nav:
  - New to Trubrics?:
    - What is Trubrics?: new_to_trubrics/what_is_trubrics.md
    - What events to track?: new_to_trubrics/what_to_track.md
    - Quickstart: new_to_trubrics/quickstart.md
    - Core concepts: new_to_trubrics/core_concepts.md
  - Track user & AI events:
    - SDKs:
      - track_events/sdks/index.md
      - Python: track_events/sdks/python.md
      - Node.js: track_events/sdks/node.md
      - Javascript (Web): track_events/sdks/javascript.md
      - Open AI: track_events/sdks/open_ai.md
    - Integrations:
      - track_events/integrations/index.md
      - Segment: track_events/integrations/segment.md
      # - Amplitude: track_events/integrations/amplitude.md
  - API reference:
    - api_reference/index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
copyright: Copyright &copy 2024 Trubrics Ltd.
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/trubrics
    - icon: fontawesome/brands/discord
      link: https://discord.gg/BPKTNxxz