site_name: trubrics docs
site_url: https://docs.trubrics.com
site_description: AI product analytics.
theme:
  name: material
  favicon: static/favicon.ico
  logo: static/logo-white.png
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Montserrat
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
extra_css:
  - stylesheets/extra.css
nav:
  - New to Trubrics?:
    - What is Trubrics?: new_to_trubrics/what_is_trubrics.md
    - What events to track?: new_to_trubrics/what_to_track.md
    - Quickstart: new_to_trubrics/quickstart.md
    - Core concepts: new_to_trubrics/core_concepts.md
  - Track user & AI events:
    - SDKs:
      - track_events/sdks/index.md
      - Server-side tracking:
        - Python:
          - User event tracking: track_events/sdks/python.md
          - LLM tracking (foundation models): track_events/sdks/open_ai.md
          - LLM tracking (frameworks): track_events/sdks/langchain.md
        - Node.js:
          - User events: track_events/sdks/node.md
          - LLM Foundation Models: track_events/sdks/open_ai.md
          - LLM Frameworks: track_events/sdks/langchain.md
      - Client-side tracking:
        - Javascript (Web): track_events/sdks/javascript.md
      # - Aleph Alpha: track_events/sdks/aleph_alpha.md
      # - Amazon Bedrock: track_events/sdks/amazon_bedrock.md
      # - Amazon SageMaker: track_events/sdks/amazon_sagemaker.md
      # - Anthropic: track_events/sdks/anthropic.md
      # - Azure Open AI: track_events/sdks/azure_openai.md
      # - Burr: track_events/sdks/burr.md
      # - Cohere: track_events/sdks/cohere.md
      # - Google Gemini: track_events/sdks/google_gemini.md
      # - Google VertexAI: track_events/sdks/google_vertexai.md
      # - Haystack: track_events/sdks/haystack.md
      # - HuggingFace Transformers: track_events/sdks/huggingface.md
      # - IBM watsonx: track_events/sdks/ibm_watsonx.md
      # - LangChain: track_events/sdks/langchain.md
      # - LlamaIndex: track_events/sdks/llamaindex.md
      # - Mistral AI: track_events/sdks/mistral_ai.md
      # - Ollama: track_events/sdks/ollama.md
      # - Open AI: track_events/sdks/open_ai.md
      # - Replicate: track_events/sdks/replicate.md
      # - together.ai: track_events/sdks/together_ai.md
    - Integrations:
      - track_events/integrations/index.md
      - Segment: track_events/integrations/segment.md
      # - Amplitude: track_events/integrations/amplitude.md
  - API reference:
    - Authentication: api_reference/authentication.md
    - HTTP API: api_reference/api_reference.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
copyright: Copyright &copy 2024 Trubrics Ltd.
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/trubrics
    - icon: fontawesome/brands/discord
      link: https://discord.gg/BPKTNxxz