site_name: trubrics docs
site_description: AI product analytics.
theme:
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
  font:
    text: Montserrat
  features:
    - navigation.tabs
    - navigation.expand
extra_css:
  - stylesheets/extra.css
nav:
  - New to Trubrics?:
    - What is Trubrics?: new_to_trubrics/what_is_trubrics.md
    - What events to track?: new_to_trubrics/what_to_track.md
    - Quickstart: new_to_trubrics/quickstart.md
    - Core concepts: new_to_trubrics/core_concepts.md
  - Track user & AI events:
    - SDKs:
      - Python: track_events/sdks/python.md
      - JS/TS: track_events/sdks/js_ts.md
      - Open AI: track_events/sdks/open_ai.md
    - Integrations:
      - Segment: track_events/integrations/segment.md
      - Amplitude: track_events/integrations/amplitude.md
  - API reference:
    - Authentication: index.md
    - JavaScript: index.md
    - REST: index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
copyright: Copyright &copy 2024 Trubrics Ltd.
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/trubrics
    - icon: fontawesome/brands/discord
      link: https://discord.gg/BPKTNxxz
    